"""Curated physical constants registry with universal and domain-specific values.

All constants are deterministic lookups -- never generated by LLM.
Values use NIST standards for universal constants and established
reference values for computational imaging.

Usage:
    from agentsim.physics.constants import lookup_constant, get_parameter_range

    c = lookup_constant("speed_of_light")  # PhysicalConstant or None
    r = get_parameter_range("wavelength", "computational_imaging")  # (min, max, unit) or None
"""

from __future__ import annotations

from agentsim.physics.models import PhysicalConstant


# ---------------------------------------------------------------------------
# Universal physical constants (NIST 2018 CODATA)
# ---------------------------------------------------------------------------

UNIVERSAL: dict[str, PhysicalConstant] = {
    "speed_of_light": PhysicalConstant(
        name="speed_of_light",
        symbol="c",
        magnitude=299792458.0,
        unit="meter / second",
        description="Speed of light in vacuum",
    ),
    "boltzmann": PhysicalConstant(
        name="boltzmann",
        symbol="k_B",
        magnitude=1.380649e-23,
        unit="joule / kelvin",
        description="Boltzmann constant",
    ),
    "planck": PhysicalConstant(
        name="planck",
        symbol="h",
        magnitude=6.62607015e-34,
        unit="joule * second",
        description="Planck constant",
    ),
    "gravitational_acceleration": PhysicalConstant(
        name="gravitational_acceleration",
        symbol="g",
        magnitude=9.80665,
        unit="meter / second ** 2",
        description="Standard acceleration of gravity",
    ),
    "stefan_boltzmann": PhysicalConstant(
        name="stefan_boltzmann",
        symbol="sigma",
        magnitude=5.670374419e-8,
        unit="watt / meter ** 2 / kelvin ** 4",
        description="Stefan-Boltzmann constant",
    ),
    "vacuum_permittivity": PhysicalConstant(
        name="vacuum_permittivity",
        symbol="epsilon_0",
        magnitude=8.8541878128e-12,
        unit="farad / meter",
        description="Vacuum electric permittivity",
    ),
    "avogadro": PhysicalConstant(
        name="avogadro",
        symbol="N_A",
        magnitude=6.02214076e23,
        unit="1 / mole",
        description="Avogadro constant",
    ),
    "gas_constant": PhysicalConstant(
        name="gas_constant",
        symbol="R",
        magnitude=8.314462618,
        unit="joule / mole / kelvin",
        description="Molar gas constant",
    ),
}


# ---------------------------------------------------------------------------
# Computational imaging domain constants
# ---------------------------------------------------------------------------

COMPUTATIONAL_IMAGING: dict[str, PhysicalConstant] = {
    # Radiometry
    "solar_irradiance": PhysicalConstant(
        name="solar_irradiance",
        symbol="E_sun",
        magnitude=1361.0,
        unit="watt / meter ** 2",
        description="Total solar irradiance at Earth",
        domain="computational_imaging",
    ),
    "typical_scene_radiance": PhysicalConstant(
        name="typical_scene_radiance",
        symbol="L_scene",
        magnitude=100.0,
        unit="watt / meter ** 2 / steradian",
        description="Typical outdoor scene radiance",
        domain="computational_imaging",
    ),
    "lambertian_max_brdf": PhysicalConstant(
        name="lambertian_max_brdf",
        symbol="f_r_max",
        magnitude=0.3183098861837907,  # 1/pi
        unit="1 / steradian",
        description="Maximum Lambertian BRDF (1/pi)",
        domain="computational_imaging",
    ),
    # Geometric optics
    "typical_focal_length": PhysicalConstant(
        name="typical_focal_length",
        symbol="f",
        magnitude=0.05,
        unit="meter",
        description="Typical camera focal length (50mm)",
        domain="computational_imaging",
    ),
    "typical_f_number": PhysicalConstant(
        name="typical_f_number",
        symbol="N",
        magnitude=2.8,
        unit="dimensionless",
        description="Typical f-number for photography",
        domain="computational_imaging",
    ),
    "thin_lens_reference": PhysicalConstant(
        name="thin_lens_reference",
        symbol="f_ref",
        magnitude=0.1,
        unit="meter",
        description="Reference thin lens focal length (100mm)",
        domain="computational_imaging",
    ),
    # Wave optics
    "visible_min_wavelength": PhysicalConstant(
        name="visible_min_wavelength",
        symbol="lambda_min",
        magnitude=380e-9,
        unit="meter",
        description="Minimum visible wavelength (violet)",
        domain="computational_imaging",
    ),
    "visible_max_wavelength": PhysicalConstant(
        name="visible_max_wavelength",
        symbol="lambda_max",
        magnitude=780e-9,
        unit="meter",
        description="Maximum visible wavelength (red)",
        domain="computational_imaging",
    ),
    "typical_coherence_length": PhysicalConstant(
        name="typical_coherence_length",
        symbol="l_c",
        magnitude=1e-6,
        unit="meter",
        description="Typical temporal coherence length",
        domain="computational_imaging",
    ),
    # Sensor models
    "typical_pixel_pitch": PhysicalConstant(
        name="typical_pixel_pitch",
        symbol="p",
        magnitude=3.45e-6,
        unit="meter",
        description="Typical CMOS sensor pixel pitch",
        domain="computational_imaging",
    ),
    "typical_read_noise": PhysicalConstant(
        name="typical_read_noise",
        symbol="sigma_read",
        magnitude=2.0,
        unit="count",
        description="Typical sensor read noise in electrons",
        domain="computational_imaging",
    ),
    "typical_full_well": PhysicalConstant(
        name="typical_full_well",
        symbol="FW",
        magnitude=10000.0,
        unit="count",
        description="Typical sensor full well capacity in electrons",
        domain="computational_imaging",
    ),
    "typical_dark_current": PhysicalConstant(
        name="typical_dark_current",
        symbol="I_dark",
        magnitude=0.1,
        unit="count / second",
        description="Typical dark current in electrons per second",
        domain="computational_imaging",
    ),
    "typical_quantum_efficiency": PhysicalConstant(
        name="typical_quantum_efficiency",
        symbol="QE",
        magnitude=0.5,
        unit="dimensionless",
        description="Typical sensor quantum efficiency",
        domain="computational_imaging",
    ),
    # Reconstruction
    "typical_psf_fwhm": PhysicalConstant(
        name="typical_psf_fwhm",
        symbol="FWHM",
        magnitude=2.0,
        unit="dimensionless",
        description="Typical point spread function FWHM in pixels",
        domain="computational_imaging",
    ),
    "nyquist_sampling_factor": PhysicalConstant(
        name="nyquist_sampling_factor",
        symbol="N_s",
        magnitude=2.0,
        unit="dimensionless",
        description="Nyquist sampling factor",
        domain="computational_imaging",
    ),
    # Noise models
    "shot_noise_reference": PhysicalConstant(
        name="shot_noise_reference",
        symbol="N_photon",
        magnitude=100.0,
        unit="count",
        description="Reference photon count for shot noise",
        domain="computational_imaging",
    ),
    "typical_snr_target": PhysicalConstant(
        name="typical_snr_target",
        symbol="SNR",
        magnitude=20.0,
        unit="dimensionless",
        description="Typical signal-to-noise ratio target",
        domain="computational_imaging",
    ),
}

# Registry mapping domain name -> constants dict
_DOMAIN_REGISTRIES: dict[str, dict[str, PhysicalConstant]] = {
    "universal": UNIVERSAL,
    "computational_imaging": COMPUTATIONAL_IMAGING,
}


# ---------------------------------------------------------------------------
# Parameter ranges (min, max, unit) for plausibility checking
# ---------------------------------------------------------------------------

PARAMETER_RANGES: dict[str, dict[str, tuple[float, float, str]]] = {
    "universal": {
        "temperature": (0.0, 1e8, "kelvin"),
        "pressure": (0.0, 1e12, "pascal"),
        "density": (1e-6, 2.5e4, "kilogram / meter ** 3"),
        "velocity": (0.0, 3e8, "meter / second"),
        "time_step": (1e-15, 1e6, "second"),
    },
    "computational_imaging": {
        "wavelength": (1e-9, 1e-3, "meter"),
        "focal_length": (1e-3, 10.0, "meter"),
        "aperture_diameter": (1e-6, 1.0, "meter"),
        "pixel_pitch": (1e-7, 1e-3, "meter"),
        "exposure_time": (1e-12, 1e3, "second"),
        "sensor_quantum_efficiency": (0.0, 1.0, "dimensionless"),
        "refractive_index": (1.0, 4.0, "dimensionless"),
        "f_number": (0.5, 128.0, "dimensionless"),
        "scene_radiance": (0.0, 1e6, "watt / meter ** 2 / steradian"),
        "pixel_count": (1.0, 1e9, "dimensionless"),
    },
}


# ---------------------------------------------------------------------------
# Lookup functions
# ---------------------------------------------------------------------------


def lookup_constant(name: str) -> PhysicalConstant | None:
    """Look up a physical constant by name.

    Checks universal constants first, then domain-specific registries.

    Args:
        name: The constant key (e.g. "speed_of_light", "solar_irradiance").

    Returns:
        PhysicalConstant if found, None otherwise.
    """
    result = UNIVERSAL.get(name)
    if result is not None:
        return result
    return COMPUTATIONAL_IMAGING.get(name)


def get_parameter_range(
    name: str,
    domain: str = "universal",
) -> tuple[float, float, str] | None:
    """Look up plausible range for a named parameter.

    Checks the specified domain first, then falls back to "universal".

    Args:
        name: Parameter name (e.g. "wavelength", "temperature").
        domain: Domain to check first (default "universal").

    Returns:
        Tuple of (min_value, max_value, unit_string) or None if not found.
    """
    domain_ranges = PARAMETER_RANGES.get(domain, {})
    result = domain_ranges.get(name)
    if result is not None:
        return result

    # Fallback to universal if not in requested domain
    if domain != "universal":
        universal_ranges = PARAMETER_RANGES.get("universal", {})
        return universal_ranges.get(name)

    return None


def list_domains() -> tuple[str, ...]:
    """Return available domain names.

    Returns:
        Tuple of domain key strings.
    """
    return tuple(_DOMAIN_REGISTRIES.keys())


def list_constants(domain: str | None = None) -> tuple[str, ...]:
    """Return constant names, optionally filtered by domain.

    Args:
        domain: If provided, only return constants from this domain.
                If None, return all constants across all domains.

    Returns:
        Tuple of constant name strings.
    """
    if domain is not None:
        registry = _DOMAIN_REGISTRIES.get(domain, {})
        return tuple(registry.keys())

    all_names: list[str] = []
    for registry in _DOMAIN_REGISTRIES.values():
        all_names.extend(registry.keys())
    return tuple(all_names)
